version: '3.7'

services:
  nginx:
    image: nginx:alpine
    
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
